url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.

contentful:
  spaces:
    - northofwine:
        space: ENV_CONTENTFUL_SPACE_ID
        access_token: ENV_CONTENTFUL_ACCESS_TOKEN
        environment: ENV_CONTENTFUL_ENVIRONMENT

page_gen-dirs: false
page_gen:
- data: contentful.spaces.northofwine.product
  template: default
  dir: utvalg
  name: product_short_name