url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "North of Wine" # the name of your site, e.g. ACME Corp.

organization:
  name: "North of Wine AS"
  id: "NO 927 128 047 MVA"
  adress:
    street: "Fosenkaia 7"
    zip: "7010"
    city: "Trondheim"
  email:
    default: "post@northofwine.no"
    order: "ordre@northofwine.no"
    invoice: "faktura@northofwine.no"

contentful:
  spaces:
    - northofwine:
        space: ENV_CONTENTFUL_SPACE_ID
        access_token: ENV_CONTENTFUL_ACCESS_TOKEN
        environment: ENV_CONTENTFUL_ENVIRONMENT
        cda_query:
          limit: 200

page_gen-dirs: false
page_gen:
- data: contentful.spaces.northofwine.product
  template: details
  dir: utvalg
  name: slug